spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:restauranteDB
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
    open-in-view: false

app:
  seed:
    enabled: true
